clothadmin/urls.py
from django.urls import path
from.import views
app_name='clothadmin'
urlpatterns=[
    path('login/',views.adminlogin,name='adminlogin'),
    path('viewproducts/',views.viewproducts,name='viewpdt'),
    path('addproducts/',views.addproducts,name='addpdt'),
    path('p_delete/<int:pid>',views.deleteproduct,name='p_delete'),
    path('sdashboard/',views.sdashboard,name='sdashboard'),
    path('addstaffs/',views.addstaffs,name='addstaffs'),
    path('p_update/<int:pid>',views.updateproduct,name='p_update'),
    path('update/',views.update,name='update'),
    path('viewstaffs/',views.viewstaffs,name='viewstaffs'),
    path('s_delete/<int:sid>',views.deletestaff,name='s_delete')


   


]

clothapp/urls.py
from django.urls import path
from.import views
app_name="clothapp"
urlpatterns=[
    path('login/',views.indexhome,name="login"),
    path('signin/',views.signin,name="signin"),
    path('',views.home,name='home'),
    path('contactus/',views.contactus,name='contactus'),
    path('dashboard/',views.Dashboard,name='dashboard'),
    path('forgetpassword/',views.forgetpassword,name='forgetpassword'),
    path('addtocart/',views.addtocart,name='addtocart'),
    path('dresses/',views.dresses,name='dresses'),
    path('sizechart/',views.sizechart,name='aboutus'),
    path('accessories/',views.accessories,name='accessories'),
    path('bags/',views.bags,name='bags'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart,name='add_to_cart'),
    path('payment/',views.payment,name='payment'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart,name='remove_from_cart'),
    path('logout/',views.LogOut,name='logout')
    
    ]

clothingproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clothapp.urls')),
    path('clothadmin/',include('clothadmin.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

clothadmin/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.TextField(max_length=50,db_column='name',null=True)   

    def __str__(self) :
        return self.name
class Product(models.Model):
    title=models.TextField(max_length=50,db_column='name',null=True)
    description=models.TextField(max_length=50,db_column='description',null=True)
    price=models.PositiveIntegerField(db_column='price',null=True)
    image=models.ImageField(upload_to='dresses',db_column='image',null=True)
    category=models.ForeignKey(Category,null=True,on_delete=models.CASCADE)
    def __str__(self) :
        return self.title
    
class Staff(models.Model):
  
    name=models.TextField(max_length=50,db_column='name',null=True)
    staffid=models.TextField(max_length=50,db_column='description',null=True)
    password=models.TextField(max_length=50,db_column='price',null=True)
    
    def __str__(self) :
        return self.name
    

clothadmin/views.py
from django.shortcuts import render,redirect
from . models import *

# Create your views here.
def adminlogin(request):
    if request.method=='POST':
        sid=request.POST['sid']
        pswd=request.POST['password']
        staff=Staff.objects.filter(staffid=sid,password=pswd).exists()
        if staff:
            return redirect("clothadmin:sdashboard")
    return render(request,'clothadmin/login.html')


def viewproducts(request):
    pdt=Product.objects.all()
    return render(request,'clothadmin/viewproducts.html',{'pdt':pdt})


def addproducts(request):
    if request.method=='POST':
        title=request.POST['title']
        description=request.POST['description']
        price=request.POST['price']
        category=request.POST['category']
        image=request.FILES['image']
        pdt=Product(title=title,description=description,price=price,image=image)
        pdt.save()
    return render(request,'clothadmin/addproducts.html')

def deleteproduct(request,pid):
    Product.objects.get(id=pid).delete()
    return redirect('clothadmin:viewpdt')

def sdashboard(request):
    return render(request,'clothadmin/stdashboard.html')

def addstaffs(request):
    if request.method=='POST':
        name=request.POST['name']
        staffid=request.POST['staffid']
        password=request.POST['password']   
        staff=Staff(name=name,staffid=staffid,password=password)
        staff.save()
    return render(request,'clothadmin/addstaffs.html')

def updateproduct(request,pid):
    pdt=Product.objects.get(id=pid)
    if request.method=='POST':
        title=request.POST['title']
        description=request.POST['description']
        price=request.POST['price']
        pdt.title=title
        pdt.description=description
        pdt.price=price
        
        pdt.save()
        return redirect("clothadmin:viewpdt")
    return render(request,"clothadmin/update.html",{'product':pdt})

def update(request):
    return render(request,'clothadmin/update.html')

def viewstaffs(request):
    staff=Staff.objects.all()
    return render(request,'clothadmin/viewstaffs.html',{'staff':staff})

def deletestaff(request,sid):
    Staff.objects.get(id=sid).delete()
    return redirect('clothadmin:viewstaffs')

clothadmin/templates/clothadmin/addproducts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      
      table{
        text-align: center;
        padding-left: 200px;
        position: relative;
        left: 480px;
        top: 100px;
        border: 1px solid black;
      
        width: 300px;
        height: 300px;
        background-color: palevioletred;

      }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid" >
      <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>  -->
          
        </ul>
      </div>
    </div>
  </nav>

  <form action="" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">
    {% csrf_token %}
   
    <table>
        <tr>
        <th><h1 style="color: white;">Add Products</h1></th>
        </tr>
        <tr>
        <th><input type="text" name="title" id="" placeholder="Title"></th>
        </tr>
        <tr>
        <th><input type="text" name="description" id="" placeholder="Description"></th>
        </tr>
        <tr>
          <th><input type="text" name="price" id="" placeholder="price"></th>
          </tr>
        <tr>
          <th><input type="text" name="category" id="" placeholder="Category"></th>
          </tr>
        
        <tr>
          <tr>
            <th><input type="file" name="image" id="" ></th>
            </tr>
          
          <tr>
        <th><button type="submit " style="background-color: blueviolet; color: white;">Save&Add</button></th>
        <!-- <th><button type="submit" style="background-color: blueviolet; width: 50px; height: 50px;">Save & Add another</button></th> -->
        </tr>
        <tr>
            <td><p id="Error" style="color:red;">{{msg}}</p></td>
            </tr>
       
       
  </table>
        
   
</form>

<script src="{% static 'script/alogin.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
</body>
</html>

clothadmin/templates/clothadmin/addstaffs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
    table{
      text-align: center;
      padding-left: 200px;
      position: relative;
      left: 480px;
      top: 100px;
      border: 1px solid black;
    
      width: 300px;
      height: 300px;
      background-color: palevioletred;
    }
  </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid" >
      <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>  -->
          
        </ul>
      </div>
    </div>
  </nav>

  <form action="" method="post" onsubmit="return validateForm()">
    {% csrf_token %}
   
    <table>
        <tr>
        <th><h1 style="color: white;">Add Staff</h1></th>
        </tr>
        <tr>
        <th><input type="text" name="name" id="" placeholder="name"></th>
        </tr>
        <tr>
        <th><input type="text" name="staffid" id="" placeholder="staffid"></th>
        </tr>
        <tr>
          <th><input type="text" name="password" id="" placeholder="password"></th>
          </tr>
        
        <tr>
        <th><button type="submit" style="background-color: blueviolet; color: white;">Save&Add</button></th>
       
        
        </tr>
        <tr>
            <td><p id="Error" style="color:red;">{{msg}}</p></td>
            </tr>
       
       
  </table>
        
   
</form>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
</body>
</html>

clothadmin/templates/clothadmin/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
       button{
       background-color:rgb(151, 4, 151);
       color: white;
       width: 100px;
       }
       body{
        background-color:palevioletred;
        text-align: center;
        padding-top: 90px;
       }
       h4{
        position: relative;
        right:250px;
       }
       h5{
        position: relative;
        right:250px;
       }
      
        
    </style>

</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-8">
                 <h4>Welcome to Hyla & Jackdaw !</h4>
                <h5>-an clothing platform that you love!</h5> 
          
            <form action="" method="post" onsubmit="return validateForm()" style="border:solid 1px white; width: 300px; height: 300px; padding: 50px; background-color:pink;">
            {% csrf_token %}
           
            <table>
                <tr>
                <th><h1> Login</h1></th>
                </tr>
                <tr>
                <th><input type="text" id="email" name="sid" placeholder="Enter your staffid"></th>
                </tr>
                <tr>
                <th><input type="text" name="password" id="password" placeholder="Enter your pasword"></th>
                </tr>
                
                <tr>
                <th><button type="submit">Login</button></th>
                </tr>
                <tr>
                    <td><p id="Error" style="color:red;">{{msg}}</p></td>
                    </tr>
               
               
          </table>
                
           
        </form>

            </div>
        </div>
    </div>
   
    <script src="{% static 'script/alogin.js' %}"></script>
   

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>     

    
    
   

    
</body>
</html>



<!-- <div class="main" style="background-image: url(https://images.unsplash.com/photo-1529641484336-ef35148bab06?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D); background-repeat: no-repeat;"> -->
       
    
   

clothadmin/templates/clothadmin/stdashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
              </li>
              
              
            </ul>
          </div>
        </div>
      </nav>
  <table>
   <tr>
    <td><button style="background-color:purple;width: 400px; height: 100px;"> <a href="{% url 'clothadmin:addpdt' %}"  style="color: white;">Add Product</a></button></td>

    <td><button style="background-color:purple;width: 400px; height: 100px;"><a href="{% url 'clothadmin:viewpdt' %}"  style="color: white;">ViewProduct</a></button></td>

    <td><button style="background-color:purple;width: 400px; height: 100px;"> <a href="{% url 'clothadmin:addstaffs' %}" style="color: white;">Add Staff</a></button></td>
</tr>
</table> 
<h1 style="padding-left: 350px; font-style: italic; color:rgb(183, 7, 183);">Welcome To Admin-Home</h1>
   <img src="{% static 'images/adminlogo.jpg' %}"  alt="" height="380px" width="800px" style="padding-left: 400px;">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

clothadmin/templates/clothadmin/update.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
table{
        text-align: center;
        padding-left: 200px;
        position: relative;
        left: 480px;
        top: 100px;
        border: 1px solid black;
      
        width: 300px;
        height: 300px;
        background-color: palevioletred;

      }
        
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
              </li>
             
              
            </ul>
          </div>
        </div>
      </nav>
    <form action="" method="post">
        {% csrf_token %}
        <table >
            <tr>
            <th><h1 style="color: white;">Update Products</h1></th>
            </tr>
            <tr>
            <th><input type="text" name="title" id="" placeholder="Title" value="{{product.title}}"></th>
            </tr>
            <tr>
            <th><input type="text" name="description" id="" placeholder="Description" value="{{product.description}}"></th>
            </tr>
            <tr>
              <th><input type="text" name="price" id="" placeholder="price" value="{{product.price}}"></th>
              </tr>
            <tr>
              <th><input type="text" name="category" id="" placeholder="Category" value="{{product.category}}"></th>
              </tr>
            
            <tr>
            <th><button type="submit " style="background-color: blueviolet; color: white;">Save&Add</button></th>
            <!-- <th><button type="submit" style="background-color: blueviolet; width: 50px; height: 50px;">Save & Add another</button></th> -->
            </tr>
            <tr>
                <td><p id="Error" style="color:red;">{{msg}}</p></td>
                </tr>
           
           
      </table>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

clothadmin/templates/clothadmin/viewproducts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,th,tr,td{
           
           text-align: center;
            padding: 40px;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>  -->
              
            </ul>
          </div>
        </div>
      </nav>

      <h1 style="padding-left: 400px; font-family: 'Times New Roman', Times, serif;  color: purple;">View Products</h1>
    <table style="padding-right: 100px;">
        <tr>
            <th>Title</th>
            <th>Image</th>
            <th>Price</th>
            <th>Description</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for i in pdt %}
        <tr>
            <td>{{i.title}}</td>
            <td><img src="{{i.image.url}}" alt="" height="50px" width="50px"></td>
            <td>{{i.price}}</td>
            <td>{{i.description}}</td>
            <td><a class="btn btn-warning" href="{% url 'clothadmin:p_update' i.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url 'clothadmin:p_delete' i.id %}" style="color:white;">delete</a></td>
        </tr>
        {% endfor %}
    </table>
    <script src="{% static 'script/alogin.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

clothadmin/templates/clothadmin/viewstaffs.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,th,tr,td{
           
           text-align: center;
            padding: 40px;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: pink;">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#" style="font-style: italic;">Hyla & Jackdaw</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'clothadmin:sdashboard' %}">Admin-Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'clothadmin:adminlogin' %}" style="color: black;">Logout</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>  -->
              
            </ul>
          </div>
        </div>
      </nav>

      <h1 style="padding-left: 400px; font-family: 'Times New Roman', Times, serif;  color: purple;">View Staffs</h1>
    <table style="padding-right: 100px;">
        <tr>
            <th>Name</th>
            <th>staffid</th>
            <th>Password</th>
            
            <th>Delete</th>
        </tr>
        {% for i in staff %}
        <tr>
            <td>{{i.name}}</td>
            
            <td>{{i.staffid}}</td>
            <td>{{i.password}}</td>
            
            <td><a class="btn btn-danger" href="{% url 'clothadmin:s_delete' i.id %}" style="color:white;">delete</a></td>
        </tr>
        {% endfor %}
    </table>
    <script src="{% static 'script/alogin.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>