clothapp/urls.py
from django.urls import path
from.import views
app_name="clothapp"
urlpatterns=[
    path('login/',views.indexhome,name="login"),
    path('signin/',views.signin,name="signin"),
    path('',views.home,name='home'),
    path('contactus/',views.contactus,name='contactus'),
    path('dashboard/',views.Dashboard,name='dashboard'),
    path('forgetpassword/',views.forgetpassword,name='forgetpassword'),
    path('addtocart/',views.addtocart,name='addtocart'),
    path('dresses/',views.dresses,name='dresses'),
    path('sizechart/',views.sizechart,name='aboutus'),
    path('accessories/',views.accessories,name='accessories'),
    path('bags/',views.bags,name='bags'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart,name='add_to_cart'),
    path('payment/',views.payment,name='payment'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart,name='remove_from_cart'),
    path('logout/',views.LogOut,name='logout')
    
    ]

clothingproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clothapp.urls')),
    path('clothadmin/',include('clothadmin.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

clothapp/models.py
from django.db import models
from clothadmin.models import Product

# Create your models here.
class Customer(models.Model):
    name=models.TextField(db_column="name",null=True)
    dob=models.TextField(db_column="dob",null=True)
    mob=models.TextField(db_column="mob",null=True)
    state=models.TextField(db_column="state",null=True)
    address=models.TextField(db_column="address",null=True)
    pincode=models.TextField(db_column="pincode",null=True)
    landmark=models.TextField(db_column="landmark",null=True)
    email=models.TextField(db_column="email",null=True)
    password=models.TextField(db_column="password",null=True)
   

    class Meta:
        db_table="customer"

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField(default=1)

class Contactus(models.Model):
    name=models.TextField(max_length=200,db_column='name',null=True)
    email=models.TextField(max_length=200,db_column='email',null=True)
    message=models.TextField(max_length=200,db_column='message',null=True)
    def __str__(self):
        return self.name

clothapp/views.py
from django.shortcuts import render,redirect
from.models import *
from clothadmin.models import *

# Create your views here.
def indexhome(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        try:
            cust=Customer.objects.get(email=email,password=password)
            request.session['customer']=cust.id
            return redirect('clothapp:dashboard')
        except Customer.DoesNotExist:
             return render(request,'clothapp/login.html',{'msg':'invalid username or password'})
        
            


        # if Customer.objects.filter(email=email,password=password).exists():
        #     return redirect('clothapp:dashboard')
        # else:
        #     return render(request,'clothapp/login.html',{'msg':'invalid username or password'})


    return render(request,'clothapp/login.html')

def signin(request):
    if request.method=='POST':
        name=request.POST ["name"]
        dob=request.POST ["dob"]
        email=request.POST ["email"]
        mob=request.POST ["mob"]
        state=request.POST["state"]
        address=request.POST ["address"]
        pincode=request.POST ["pincode"]
        password=request.POST ["password"]
        landmark=request.POST ["landmark"]
        customer=Customer(name=name,dob=dob,email=email,mob=mob,state=state,address=address,pincode=pincode,password=password,landmark=landmark)
        customer.save()
        return redirect("clothapp:login")
    return render(request,'clothapp/signin.html')

def home(request):
    return render (request,'clothapp/home.html')

def contactus(request):
    
    if request.method=='POST':
        name=request.POST ["name"]
        email=request.POST ["email"]
        message=request.POST ["message"]
        
        cont=Contactus(name=name,email=email,message=message)
        cont.save()
       
    
    return render(request,'clothapp/contactus.html')

def Dashboard(request):
    if 'customer' in request.session:
     return render(request,'clothapp/dashboard.html')
    else:
        return render(request,'clothapp/home.html')

def forgetpassword(request):
    return render(request,'clothapp/forgetpassword.html')

def addtocart(request):
    if 'customer' in request.session:
        cart_items=Cart.objects.all()
        total_price=sum(item.product.price * item.quantity  for item in cart_items)
        total_price_per_item=[]
        grand_total=0

        for item in cart_items:
            item_total=item.product.price * item.quantity
       
            total_price_per_item.append({'item': item,'total':item_total})
            grand_total += item_total
        return render(request,'clothapp/addtocart.html', {'cart_items':cart_items,'grand_total':grand_total,'total_price':total_price})
    else:
        return render(request,'clothapp/home.html')
    


def remove_from_cart(request,product_id):
    if 'customer' in request.session:
      if request.method=='POST':
        product=Product.objects.get(id=product_id)
        cart_item=Cart.objects.get(product=product)
        cart_item.delete()
      return redirect('clothapp:addtocart')  
    else:
        return render(request,'clothapp/home.html')
      


def dresses(request):
    if 'customer' in request.session:
      cat=Category.objects.get(name='Dresses')
      pdts=Product.objects.filter(category=cat)
    #   return render(request,'clothapp/dresses.html')
      return render(request,'clothapp/dresses.html',{'product':pdts})
    else:
        return render(request,'clothapp/home.html')
   
    

def sizechart(request):
    return render(request,'clothapp/sizechart.html')

def accessories(request):
    if 'customer' in request.session:
     cat=Category.objects.get(name='Accessories')
     pdts=Product.objects.filter(category=cat)
     return render(request,'clothapp/accessories.html',{'product':pdts})
    else:
        return render(request,'clothapp/home.html')
    

def bags(request):
    if 'customer' in request.session:
     cat=Category.objects.get(name='Bags')
     pdts=Product.objects.filter(category=cat)
     return render(request,'clothapp/bags.html',{'product':pdts})
    else:
        return render(request,'clothapp/home.html')

def add_to_cart(request,product_id):
    if 'customer' in request.session:
       if request.method=='POST':
        product=Product.objects.get(id=product_id)
        cart_item,created=Cart.objects.get_or_create(product=product)
        if not created:
            cart_item.quantity += 1
            cart_item.save()

        return redirect('clothapp:addtocart') 
    else:
        return render(request,'clothapp/home.html')
       

def payment(request):
    if 'customer' in request.session:
     return render(request,'clothapp/payment.html')
    else:
        return render(request,'clothapp/home.html')

def LogOut(request):
    if 'customer' in request.session:
        del request.session['customer']
        return redirect('clothapp:home')

clothapp/templates/clothapp/accessories.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
      
  {% for i in product %}
      <div class="col-4">
  
  <div class="card" style="width: 18rem;">
      <img src=" {{i.image.url}}" class="card-img-top" alt="..." height="280px">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <p class="card-text">{{ i.description }}  <a href=""></a></p>

        <form method="post" action="{% url 'clothapp:add_to_cart' i.id %}">
          {% csrf_token %}
          <div class="quantity" style="display: none;">
            <input type="number" name="quantity" id="quantity" value="1" min="1" required>
  
          </div>
          <button type="submit" class="btn btn-primary">Add to cart</button>
  
        </form>
        
        <p>{{i.price}}</p>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
</div>

{% endblock %}

clothapp/templates/clothapp/addtocart.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}

<style>
    .add{
        background-color: palevioletred;
        font-family: 'Times New Roman', Times, serif;
        font-weight: bolder;
    }

    h2{
        color: black;
        padding-top: 20px;
       
    /* height: 20px; */
   
    }
   
   
   input{
    width: 50px;
   }
   
   .tb{
    margin-bottom: 80px;
    
   }
   tr th{
    padding-left: 130px;
   }

</style>

<div class="add">
    <h1>ADD TO CART</h1>
</div>

<div class="con">
    <table class="tb">
        <tr class="row1"  >
        
            <th><h2>Products</h2></th>
            <th><h2>Price</h2></th>
            <th><h2>Quantity</h2></th>
            <th><h2>Delete</h2></th>
        </tr>
       
        {% for item in cart_items %}
        <tr>
            <th><img src="{{item.product.image.url}}" alt="" height="90px"></th>
            <th><h6>${{item.product.price}}</h6></th>
            <th>{{item.quantity}}<th>
                <form method="post" action="{% url 'clothapp:remove_from_cart' item.product.id %}">
                    {% csrf_token %}
                    
                    <button type="submit" class="btn btn-danger" style="color:white;">Delete</button>
            
                  </form>
        </tr>
        
        {% endfor %}
        <tr>
            <th><h2>Grand total</h2></th>
            <th>{{total_price}}</th>
        </tr>
    </table>
  


    <tr><a class="btn btn-success btn-lg " href="{% url 'clothapp:payment' %}" style="color: white; background-color: palevioletred; position: relative; bottom: 90px; height: 40px;">Buy Now</a></tr>
</div>












{% endblock %}

clothapp/templates/clothapp/bags.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
      
  {% for i in product %}
      <div class="col-4">
  
  <div class="card" style="width: 18rem;">
      <img src=" {{i.image.url}}" class="card-img-top" alt="..." height="280px">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <p class="card-text">{{ i.description }}  <a href=""></a></p>

        <form method="post" action="{% url 'clothapp:add_to_cart' i.id %}">
          {% csrf_token %}
          <div class="quantity" style="display: none;">
            <input type="number" name="quantity" id="quantity" value="1" min="1" required>
  
          </div>
          <button type="submit" class="btn btn-primary">Add to cart</button>
  
        </form>
        
        <p>{{i.price}}</p>
      </div>
    </div>
  </div>
  {% endfor %}

       



</div>
</div>
{% endblock %}

clothapp/templates/clothapp/contactus.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}
{% block content %}

    <style>
    table{
       border: 1px solid black;
       border-radius:1px;
       width: 320px;
       height: 350px;
       padding-right: 50px;
       padding-left: 20px;
       padding-bottom: 30px;
     background-image: url(https://images.unsplash.com/photo-1633815475307-884ad652b80b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8NXwyQUcxRkRJU3VsVXx8ZW58MHx8fHx8);
       
       
    }
    .contact{
        padding-left: 400px;
        padding-top:120px;
    }

    

    input{
        
        width: 250px;
        border-radius: 5px;
    }

    button{
        width: 250px;
        color: white;
        background-color:rgb(107, 4, 107);
        border-radius: 5px;
    }
    h1{
        color:white;
        

    }

    .containerfluid{
        height: 600px;
    
    }
    </style>
    <script>
        function validateForms(){
    var email=document.getElementById("email").value
    var name=document.getElementById("name").value 
    var message=document.getElementById("message").value
    
    

    if (email===""||message===""||name===""){
       // alert('hhhh')
        document.getElementById("Error").innerHTML="All fields must be filled out"
       
        
        return false
    }
    
    
    else{
        alert('message sent successfully')
        // document.getElementById("Error").innerHTML="Message sent successfully"
    return true
    }

}
    </script>

    <div class="containerfluid" style="background-image: url(https://images.unsplash.com/photo-1656231877753-1658b926365f?q=80&w=1962&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);background-repeat: no-repeat ;background-size: cover;">
    <div class="row">
        <div class="col3"></div>
        <div class="col6">
            <form action="" method="post" onsubmit="return validateForms()">
                {% csrf_token %}
                <div class="contact">
                    <table>
                        <tr>
                        <th><h1>Contact us</h1></th>
                        </tr>
                        <tr>
                        <th><input type="text" name="name" id="name" placeholder="Name"></th>
                        </tr>
                        <tr>
                        <th><input type="email" name="email" id="email" placeholder="Email"></th>
                        </tr>
                        <tr>
                        <th><input type="text" name="message" id="message" placeholder="write a message"></th>
                        </tr>
                        <tr>
                        <th><button type="submit">send</button></th>
                        </tr>
                        <tr>
                        <th><p id="Error" style="color:red;">{{msg}}</p></th>
                            </tr>
                    </table>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    </div>
        


    {% endblock %}
   

clothapp/templates/clothapp/dashboard.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}
{% block content %}


<style>
    .discount{
        color: white;
        font-family: 'Times New Roman', Times, serif;
        height: 200px;
        width: 1210px;
        background-color:darkseagreen;
    }
</style>

<div class="discount">
     <p style="font-weight: bold;">DON'T MISS OUT OUR MEGASALE EXTRAVAGANZA!</p>
    <P style="font-weight: bold;">SHOP NOW AND UNLOCK EXCLUSIVE DISCOUNTS OF UPTO 50% ON ALL YOUR FAVORITE PRODUCTS</P> 
    <h1 style="font-weight: bolder;">SALE!</h1>
    
</div>





<div class="card-container">
    
    
    <div class="card" style="width: 300px;" >
        <P style="font-weight: bolder;">NEW ARRIVALS!</P>
      <img src=" {% static 'images/naw1.jpeg' %}" alt="" >
        <p>Find perfect dresses that fits you</p>
        <a href="{% url 'clothapp:dresses' %}"><p class="catbtn" style="color: palevioletred;">Let's Go</p></a>
        
    </div>

    
    <div class="card" style="width: 300px;">
        <P style="font-weight: bolder;">NEW ARRIVALS!</P>
      <img src="{% static 'images/jaw1.jpeg' %}" alt="">
        
        <p>Discover stylish accessories</p>
        <a href="{% url 'clothapp:accessories' %}"><p class="catbtn" style="color: palevioletred;">Let's Go</p></a>
        
    </div>

    
    <div class="card" style="width: 300px;">
        <P style="font-weight: bolder;">NEW ARRIVALS!</P>
      <img src="{% static 'images/bag1.jpeg' %}" alt="" height="420px">
        
        <p>Explore Fashionable bags</p>
        <a href="{% url 'clothapp:bags' %}"><p class="catbtn" style="color: palevioletred;">Let's Go</p></a>
       
    </div>

   
</div>



{% endblock %}

clothapp/templates/clothapp/dresses.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}


<div class="container">
<div class="row">
    
{% for i in product %}
    <div class="col-4">

<div class="card" style="width: 18rem;">
    <img src=" {{i.image.url}}" class="card-img-top" alt="..." height="280px">
    <div class="card-body">
      <h5 class="card-title">{{ i.title }}</h5>
      <p class="card-text">{{ i.description }}  <a href=""></a></p>



      <form method="post" action="{% url 'clothapp:add_to_cart' i.id %}">
        {% csrf_token %}
        <div class="quantity" style="display: none;">
          <input type="number" name="quantity" id="quantity" value="1" min="1" required>

        </div>
        <button type="submit" class="btn btn-primary">Add to cart</button>

      </form>
      <p>{{i.price}}</p>
    </div>
  </div>
</div>
{% endfor %}



</div>
</div>
{% endblock %}

clothapp/templates/clothapp/forgetpassword.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}
{% block content %}
    <style>
    table{
        position: relative;
        bottom: 80px;
       border: 1px solid black;
       border-radius:5px;
       width: 320px;
       height: 380px;
       padding-right: 50px;
       padding-left: 20px;
       padding-bottom: 30px;
     background-image: url(https://images.unsplash.com/photo-1608178398319-48f814d0750c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fHw%3D);
       
       
    }
    .pswrd{
        padding-left: 400px;
        padding-top:120px;
    }
    h6{
        color: white;
    }
    

    input{
        
        width: 250px;
        border-radius: 5px;
    }

    button{
        width: 250px;
        color: white;
        background-color:rgb(107, 4, 107);
        border-radius: 5px;
    }
    h1{
        color:white;
        

    }

    .containerfluid{
        height: 600px;
    
    }
    
    </style>


<script>
    function validateFormss(){
    var email=document.getElementById("email").value
    var name=document.getElementById("name").value 
   
    

    if (email===""||name===""){
       // alert('hhhh')
        document.getElementById("Error").innerHTML="All fields must be filled out"
       
        
        return false
    }
    
    
    else{
        alert('message sent to the email successfully')
        // document.getElementById("Error").innerHTML="Message sent successfully"
    return true
    }

}
</script>

    <div class="containerfluid" style="background-image: url(https://images.unsplash.com/photo-1533134755454-9549758f0e06?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);background-size: cover;background-repeat: initial;">
        <form action="" method="POST" onsubmit="return validateFormss()">
            {% csrf_token %}
          <div class="row">
            <div class="col3"></div>
            <div class="col6">
                <div class="pswrd">
                <table>
                    <tr>
                    <th><h1>Forget Password?</h1></th>
                    </tr>
                    <tr>
                    <th><h6>we'll send an email to your registered address,please click the link provided in the email inorder to  change your password</h6></th>
                    </tr>
                    <tr>
                    <th><input type="text" name="name" id="name" placeholder="Name"></th>
                    </tr>
                    <tr>
                    <th><input type="email" name="email" id="email" placeholder="Email"></th>
                    </tr>
                    <tr>
                    <th><button type="submit">send</button></th>
                    </tr>
                    <tr>
                        <th><p id="Error" style="color:red;">{{msg}}</p></th>
                            </tr>
                </table>
            </div>

            </div>
            <div class="col3"></div>
          </div>
        </form>
    </div>




    {% endblock %}

clothapp/templates/clothapp/login.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}
<style>
    h4{
        color: white;
        font-family: 'Times New Roman', Times, serif;
        font-style: italic;
        font-weight: lighter;
    }
    h5{
        color: white;
        font-family: 'Times New Roman', Times, serif;
        font-style: italic;
        font-weight: lighter;
    }
    h6{
        color: white;
    }
    
</style>

<div class="main" style="background-image: url(https://images.unsplash.com/photo-1529641484336-ef35148bab06?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D); background-repeat: no-repeat;">
       
    
   
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h4>Welcome to Hyla & Jackdaw !</h4>
            <h5>-an clothing platform that you love!</h5>
        </div>
        <div class="col-2"></div>
    </div>
    
    <div class="row">
        <div class="col-4"></div>

    
    <div  class=" col-4 loginbox" style="background-image: url(https://images.unsplash.com/photo-1544365558-35aa4afcf11f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHx8);">
        <form action="" method="post" onsubmit="return validateForm()">
        {% csrf_token %}
       
        <table>
            <tr>
            <th><h1>Login</h1></th>
            </tr>
            <tr>
            <th><input type="email" id="email" name="email" placeholder="Enter your email"></th>
            </tr>
            <tr>
            <th><input type="text" name="password" id="password" placeholder="Enter your pasword"></th>
            </tr>
            <tr>
            <th><a href="{% url 'clothapp:forgetpassword' %}"><span>Forgot password?</span></a></th>
            </tr>
            <tr>
            <th><button type="submit">Login</button></th>
            </tr>
            <tr>
                <td><p id="Error" style="color:red;">{{msg}}</p></td>
                </tr>
            <tr>
            <th><h6>Don't have an account? <span ><a href="{% url 'clothapp:signin' %}">Signup</a></span></h6></th>
            </tr>
           
      </table>
            
       
    </form>
    </div>
    <div class="col-4"></div>

    
        
        
        
    </div>

</div>
    
    {% endblock %}
   

clothapp/templates/clothapp/masterpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      .footer{
        background-color: black;
      }
      .navbar-brand{
        font-family: 'Times New Roman', Times, serif;
        font-style: italic;
        
      }
     
    </style>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
     <link rel="stylesheet" href="{% static 'css/login.css' %}">
     <link rel="stylesheet" href="{% static 'css/signup.css' %}">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
   
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Hyla & Jackdaw</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'clothapp:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'clothapp:aboutus' %}">About us</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black;">
                    Account
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'clothapp:login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'clothapp:logout' %}">Logout</a></li>
                   
                    <li><a class="dropdown-item" href="{% url 'clothapp:contactus' %}">contact us</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black;">
                    Categories
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'clothapp:dresses' %}">Dresses</a></li>
                    <li><a class="dropdown-item" href="{% url 'clothapp:accessories' %}">Accessories</a></li>
                   
                    <li><a class="dropdown-item" href="{% url 'clothapp:bags' %}">Bags</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'clothapp:addtocart' %}">Cart</a>
                </li>
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </div>
    </div>

{% block content%}
{% endblock %}
<div class="footer">
  <h6 style="color: white; font-weight: lighter;">©Copyright.All rights reserved</h6>
</div>
</div>






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'script/login.js' %}"></script>
    <script src="{% static 'script/signin.js' %}"></script>
   
</body>
</html>

clothapp/templates/clothapp/payment.html
{% extends 'clothapp/masterpage.html' %}
{% load static %}

{% block content %}

<div>
    <h1 style="background-color: palevioletred;">Payment</h1>
</div>

<div><h6>Enter your Payment details</h6></div>


<div class="pd">
    <table>
    <form action="">
       <tr>
        <td><label for="" style="color: black; padding-left: 300px;">card number</label></td>
        <td><input type="text"></td>
        <td><label for="" style="color: black;">country</label></td>
        <td><input type="text"></td>
    </tr>
    </form>
</table>
</div>

<div>
    <h3>Or</h3>
</div>


<div>
    Cash on delivery
</div>
<div>
    <table>
        <tr>
           <td><label for="" style="color: black; padding-left: 400px;">Enter your full address</label></td>
           <td><input type="text" name="" id=""></td>
        </tr>

    </table>
</div>

<div><button style="margin-top: 100px; position: relative; bottom: 50px;">Confirm Order</button></div>












{% endblock %}